# Site settings
title: sebbrochet
header-img: img/home-bg.jpg
email: contact@sebbrochet.com
description: "Consulting CTO - Problématiques d'infrastructure au quotidien"
baseurl: "/"
url: "https://sebbrochet.github.io"
twitter_username: sebbrochet
github_username:  sebbrochet
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
